name: gh-ci
on:
  pull_request
jobs:
  test_sdformat_urdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ros-distro: "rolling"
            docker-image: "ubuntu:24.04"
    container:
      image: ${{ matrix.docker-image }}
    steps:
      - uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}
          use-ros2-testing: true
      - name: Build and test all packages
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros-distro }}
